### ISSUE TITLE
CRS issue in Trajectools

### ISSUE THREAD

**Issue by adeverakonda** [anitagraser/qgis-processing-trajectory#10]
I wish to use Trajectools in QGIS, but CRS handling in Geopandas has changed. When will Trajectools also be updated?

**Comment by k1th** [comment]
just install the old version:
`conda install geopandas=0.6.3`

**Comment by anitagraser** [comment]
Depending on the OS, it's easier to hot-fix the plugin than to downgrade GeoPandas.

Anyway, I'll publish an updated version soon.
