### ISSUE TITLE
Couldn't load plugin 'processing_trajectory'

### ISSUE THREAD

**Issue by adamgarbo** [anitagraser/qgis-processing-trajectory#13]
I am attempting to install the Trajectools plugin on macOS with QGIS 3.10, however, am currently faced with the following error:

> ModuleNotFoundError: No module named 'geopandas'

I have tried installing geopandas using both `pip install geopandas` and `conda install geopandas` but to no avail. I am able to import geopandas when working from within Python 3 without any issues.

I'd appreciate any insights into this issue!

![Screen Shot 2020-04-10 at 5 39 51 PM](https://user-images.githubusercontent.com/22924092/79024947-66c5df80-7b52-11ea-8140-7f0691ec5dd9.png)

**Comment by goatsweater** [comment]
QGIS ships with it's own version of Python on MacOS. Using `pip install geopandas` (or conda) will install to the system default location for the Python that comes with MacOS (which QGIS ignores). That is also why `import geopandas` works when you are using Python outside QGIS.

I'm not sure how to trigger `pip install` from within QGIS though.

**Comment by adamgarbo** [comment]
Closed as unresolved.
