### ISSUE TITLE
Timestamp format

### ISSUE THREAD

**Issue by iqnaul** [anitagraser/qgis-processing-trajectory#15]
Hi @anitagraser 
I initially have timestamp on my trajectory data in this format 'yyyy-mm-dd hh:mm:ss.ss+00' however when running the "Trajectories from Point Layer" it always failed and saying that the timestamp is incorrect.
I tried to create a new field that contains on the time in this format 'hh:mm:ss" and put '%H:%M:%S' on the parameter but it returned another error that mentioned ValueError: time data '-01-04 1' does not match format '%H:%M:%S'

Can help on this?

Thank you

**Comment by anitagraser** [comment]
Try yyyy-mm-dd hh:mm:ss instead. The decimal seconds and or time zone information is likely the source of the issue.
