### ISSUE TITLE
Add option to add stops from the stop detection algorithm?

### ISSUE THREAD

**Issue by kinow** [anitagraser/qgis-processing-trajectory#17]
Hi,

I used MovingPandas to create a trajectory from a given series of GPS points, both in Python & QGIS. And added the stops detected in the trajectory in Python.

I wanted to let some co-workers experiment with the data, so tried this plug-in, but from what I could tell this plug-in can only create the trajectory. Are there plans to add the option to also add detected stops too?

Thanks!
Bruno

p.s.: I haven't tried the smooth trajectory yet, but having that in the plug-in would be nice as well

**Comment by anitagraser** [comment]
Hi Bruno. This enhancement is part of #18, which representes the larger effort to expose all MovingPandas functionality in QGIS.

**Comment by kinow** [comment]
Ah! I will close this one and add a comment there then. Thanks @anitagraser !
