### ISSUE TITLE
homepage, tracker, repository in metadata.txt point to wrong URL

### ISSUE THREAD

**Issue by sfkeller** [anitagraser/qgis-processing-trajectory#7]
Hallo Anita :-). 

As a consequence of renaming (#6) homepage, tracker, repository in metadata.txt now point to https://github.com/anitagraser/processing-trajectory but should be https://github.com/anitagraser/qgis-processing-trajectory . 

And BTW you could also mention the GeoPandas dependency in "about".

**Comment by anitagraser** [comment]
Thanks, fixed in https://github.com/anitagraser/qgis-processing-trajectory/commit/210b62eda61ea267491af0eea8c1831135bbb5dc

**Comment by anitagraser** [comment]
And added GeoPandas note to about: https://plugins.qgis.org/plugins/processing_trajectory/
