### ISSUE TITLE
Cannot install QGIS trajectools

### ISSUE THREAD

**Issue by ArnoGitHub** [anitagraser/qgis-processing-trajectory#9]
I am trying to install Trajectools but have an error even if I have followed (nearly) all the installation protocol (see below).

Two differences:
- I have not done defined the GDAL version in the environment variables. I don't know how to do it (can you help on this ?)
- The version of Fiona is different from what was indicated in your protocol

### In the OSGeo (seems all went well)

![OSGeoShell](https://user-images.githubusercontent.com/15986881/55894013-54a01280-5b87-11e9-9aab-41ad83c0061a.png)

### In QGIS while trying to install Trajectools

![QGISerror](https://user-images.githubusercontent.com/15986881/55894071-76999500-5b87-11e9-9dc2-5924604d6fcd.png)

**Comment by anitagraser** [comment]
Looks like QGIS is not installed from OSGeo4W but using the stand-alone installer. Try installing QGIS from OSGeo4W instead

**Comment by ArnoGitHub** [comment]
That solve my problem
